version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestForce2Project
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer/TestForce2Project
  gitUsername: deemashlayer
  gitBranch: main
